### ISSUE TITLE
0.1.1 tarball contains build directory

### ISSUE THREAD

**Issue by buztard** [christkv/bson-ext#2]
The tarball at http://registry.npmjs.org/bson-ext/-/bson-ext-0.1.1.tgz contains the build directory and architecture specific binaries:
package/build/Release/bson.node: Mach-O 64-bit x86_64 bundle

Speeds up installation but doesn't match everybody's architecture :)

**Comment by nathanpeck** [comment]
Ah this makes sense.... That's why my Ubuntu machines are getting Mac builds and failing to load the BSON module.

What a fuck up. I hope the maintainer is able to deprecate version 0.1.1 and fix this soon.

**Comment by kmcclosk** [comment]
Same issue here. Please fix.

**Comment by christkv** [comment]
published 0.1.2 let me know if it works now.

**Comment by nathanpeck** [comment]
Working again! Thanks man!

**Comment by imlucas** [comment]
@buztard apologies.  What you described is basically what we're trying to achieve with [node-pre-gyp](http://npm.im/node-pre-gyp) support: [travis](https://travis-ci.org/imlucas/bson-ext) and [appveyor](https://ci.appveyor.com/project/imlucas/bson-ext) compile and push artifacts to S3 for windows and nix.  Then when you run `npm install`, `node-pre-gyp` figures out the S3 key you need and just downloads it (if it's not on S3 yet, it just falls back to compiling like it used to).

**Comment by imlucas** [comment]
You can verify it's a pre-compiled by the "install via remote" like so:

```
> bson-ext@0.1.2 install /Users/lucas/lone/node_modules/bson/node_modules/bson-ext
> node-pre-gyp install --fallback-to-build

[bson-ext] Success: "/Users/lucas/lone/node_modules/bson/node_modules/bson-ext/build/Release/bson.node" is installed via remote
```

**Comment by nathanpeck** [comment]
I think that precompiling the binaries is an interesting approach, but it seems like it could lead to more issues similar to this one, where the precompiled binary doesn't work on the target system.

Fundamentally as a developer I would rather see my binary build fail so I know that I'm missing a dependency or in some other way have my environment set up incorrectly rather than just seeing a confusing error message because the prebuilt binary isn't compatible with my system.

Of course I can always fallback to the manual local build but that only works if I am installing `bson-ext` directly and manually. If like me you are installing `bson` which in turns installs `bson-ext` automatically via its package.json you end up having much less control over what happens.

**Comment by christkv** [comment]
its mostly for windows users

**Comment by imlucas** [comment]
Much smarter people than us have figured this out (@springmeyer) and maintain the ABI compat tables.   

See any one of the below for much more confusing error messages:

- mongodb/js-bson#120 
- mongodb/js-bson#118 
- mongodb/js-bson#114 
- mongodb/js-bson#111 
- iojs/io.js#1245 
- iojs/io.js#1099

**Comment by christkv** [comment]
fixed, only windows binary builds happening now
